/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_public_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article Detail */
        get: operations["article_detail_api_public_articles__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_public_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/sitemap-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sitemap */
        get: operations["sitemap_api_public_sitemap_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_admin_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_admin_articles_get"];
        put?: never;
        /** Create Article */
        post: operations["create_article_api_admin_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_admin_articles__article_id__get"];
        put?: never;
        post?: never;
        /** Delete Article */
        delete: operations["delete_article_api_admin_articles__article_id__delete"];
        options?: never;
        head?: never;
        /** Update Article */
        patch: operations["update_article_api_admin_articles__article_id__patch"];
        trace?: never;
    };
    "/api/admin/articles/{article_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Article */
        post: operations["publish_article_api_admin_articles__article_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles/{article_id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish Article */
        post: operations["unpublish_article_api_admin_articles__article_id__unpublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_admin_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_admin_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_api_admin_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_admin_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_admin_categories__category_id__patch"];
        trace?: never;
    };
    "/api/admin/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Authors */
        get: operations["list_authors_api_admin_authors_get"];
        put?: never;
        /** Create Author */
        post: operations["create_author_api_admin_authors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Author */
        get: operations["get_author_api_admin_authors__author_id__get"];
        put?: never;
        post?: never;
        /** Delete Author */
        delete: operations["delete_author_api_admin_authors__author_id__delete"];
        options?: never;
        head?: never;
        /** Update Author */
        patch: operations["update_author_api_admin_authors__author_id__patch"];
        trace?: never;
    };
    "/api/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_api_admin_media_get"];
        put?: never;
        /** Upload Media */
        post: operations["upload_media_api_admin_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Media */
        delete: operations["delete_media_api_admin_media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/editorial/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Editorial Articles */
        get: operations["editorial_articles_api_admin_editorial_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/editorial/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Editorial Usage */
        get: operations["editorial_usage_api_admin_editorial_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/editorial/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Editorial Generate */
        post: operations["editorial_generate_api_admin_editorial_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/editorial/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Editorial Review */
        post: operations["editorial_review_api_admin_editorial_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/editorial/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Editorial Apply */
        post: operations["editorial_apply_api_admin_editorial_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyInput */
        ApplyInput: {
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /** Selectedfields */
            selectedFields: ("excerpt" | "metaDescription" | "tags")[];
            values: components["schemas"]["ApplyValues"];
        };
        /** ApplyResponse */
        ApplyResponse: {
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /**
             * Articledocumentid
             * Format: uuid
             */
            articleDocumentId: string;
            /**
             * Applied
             * @constant
             */
            applied: true;
            /** Draftrevision */
            draftRevision: number;
            /** Selectedfields */
            selectedFields: ("excerpt" | "metaDescription" | "tags")[];
        };
        /** ApplyValues */
        ApplyValues: {
            /** Excerpt */
            excerpt?: string | null;
            /** Metadescription */
            metaDescription?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ArticleCreate */
        ArticleCreate: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Slug
             * @default
             */
            slug: string;
            /** Body */
            body?: (components["schemas"]["Paragraph"] | components["schemas"]["Heading"] | components["schemas"]["Quote"] | components["schemas"]["ListBlock"] | components["schemas"]["ImageBlock"])[];
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /**
             * Metadescription
             * @default
             */
            metaDescription: string;
            /** Tags */
            tags?: string[];
            /** Categorydocumentid */
            categoryDocumentId?: string | null;
            /** Authordocumentid */
            authorDocumentId?: string | null;
            /** Covermediadocumentid */
            coverMediaDocumentId?: string | null;
            /**
             * Coveralt
             * @default
             */
            coverAlt: string;
            /**
             * Covercaption
             * @default
             */
            coverCaption: string;
            /**
             * Imagecredit
             * @default
             */
            imageCredit: string;
            /**
             * Imagesourceurl
             * @default
             */
            imageSourceUrl: string;
            /** Sourcelinks */
            sourceLinks?: components["schemas"]["SourceLink"][];
            /** Informationcheckedat */
            informationCheckedAt?: string | null;
            /**
             * Operationalclaims
             * @default false
             */
            operationalClaims: boolean;
            /**
             * Regionlabel
             * @default
             */
            regionLabel: string;
            /**
             * Featured
             * @default false
             */
            featured: boolean;
        };
        /** ArticleDraft */
        ArticleDraft: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Slug
             * @default
             */
            slug: string;
            /** Body */
            body?: (components["schemas"]["Paragraph"] | components["schemas"]["Heading"] | components["schemas"]["Quote"] | components["schemas"]["ListBlock"] | components["schemas"]["ImageBlock"])[];
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /**
             * Metadescription
             * @default
             */
            metaDescription: string;
            /** Tags */
            tags?: string[];
            /** Categorydocumentid */
            categoryDocumentId?: string | null;
            /** Authordocumentid */
            authorDocumentId?: string | null;
            /** Covermediadocumentid */
            coverMediaDocumentId?: string | null;
            /**
             * Coveralt
             * @default
             */
            coverAlt: string;
            /**
             * Covercaption
             * @default
             */
            coverCaption: string;
            /**
             * Imagecredit
             * @default
             */
            imageCredit: string;
            /**
             * Imagesourceurl
             * @default
             */
            imageSourceUrl: string;
            /** Sourcelinks */
            sourceLinks?: components["schemas"]["SourceLink"][];
            /** Informationcheckedat */
            informationCheckedAt?: string | null;
            /**
             * Operationalclaims
             * @default false
             */
            operationalClaims: boolean;
            /**
             * Regionlabel
             * @default
             */
            regionLabel: string;
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
            /** Revision */
            revision: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Publishedat */
            publishedAt: string | null;
            /** Publishedrevision */
            publishedRevision: number | null;
        };
        /** ArticlePatch */
        ArticlePatch: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Slug
             * @default
             */
            slug: string;
            /** Body */
            body?: (components["schemas"]["Paragraph"] | components["schemas"]["Heading"] | components["schemas"]["Quote"] | components["schemas"]["ListBlock"] | components["schemas"]["ImageBlock"])[];
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /**
             * Metadescription
             * @default
             */
            metaDescription: string;
            /** Tags */
            tags?: string[];
            /** Categorydocumentid */
            categoryDocumentId?: string | null;
            /** Authordocumentid */
            authorDocumentId?: string | null;
            /** Covermediadocumentid */
            coverMediaDocumentId?: string | null;
            /**
             * Coveralt
             * @default
             */
            coverAlt: string;
            /**
             * Covercaption
             * @default
             */
            coverCaption: string;
            /**
             * Imagecredit
             * @default
             */
            imageCredit: string;
            /**
             * Imagesourceurl
             * @default
             */
            imageSourceUrl: string;
            /** Sourcelinks */
            sourceLinks?: components["schemas"]["SourceLink"][];
            /** Informationcheckedat */
            informationCheckedAt?: string | null;
            /**
             * Operationalclaims
             * @default false
             */
            operationalClaims: boolean;
            /**
             * Regionlabel
             * @default
             */
            regionLabel: string;
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** Revision */
            revision: number;
        };
        /** Author */
        Author: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Bio
             * @default
             */
            bio: string;
            /** Avatarmediadocumentid */
            avatarMediaDocumentId?: string | null;
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
        };
        /** AuthorInput */
        AuthorInput: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Bio
             * @default
             */
            bio: string;
            /** Avatarmediadocumentid */
            avatarMediaDocumentId?: string | null;
        };
        /** Body_upload_media_api_admin_media_post */
        Body_upload_media_api_admin_media_post: {
            /** File */
            file: string;
            /**
             * Credit
             * @default
             */
            credit: string;
            /**
             * Sourceurl
             * @default
             */
            sourceUrl: string;
            /**
             * License
             * @default
             */
            license: string;
        };
        /** Category */
        Category: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
        };
        /** CategoryInput */
        CategoryInput: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** Cover */
        Cover: {
            /** Url */
            url: string;
            /** Alt */
            alt: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** Data[ArticleDraft] */
        Data_ArticleDraft_: {
            data: components["schemas"]["ArticleDraft"];
        };
        /** Data[Author] */
        Data_Author_: {
            data: components["schemas"]["Author"];
        };
        /** Data[Category] */
        Data_Category_: {
            data: components["schemas"]["Category"];
        };
        /** Data[Deleted] */
        Data_Deleted_: {
            data: components["schemas"]["Deleted"];
        };
        /** Data[LoggedOut] */
        Data_LoggedOut_: {
            data: components["schemas"]["LoggedOut"];
        };
        /** Data[Media] */
        Data_Media_: {
            data: components["schemas"]["Media"];
        };
        /** Data[PublicArticleDetail] */
        Data_PublicArticleDetail_: {
            data: components["schemas"]["PublicArticleDetail"];
        };
        /** Data[SessionDTO] */
        Data_SessionDTO_: {
            data: components["schemas"]["SessionDTO"];
        };
        /** Data[list[ArticleDraft]] */
        Data_list_ArticleDraft__: {
            /** Data */
            data: components["schemas"]["ArticleDraft"][];
        };
        /** Data[list[Author]] */
        Data_list_Author__: {
            /** Data */
            data: components["schemas"]["Author"][];
        };
        /** Data[list[Category]] */
        Data_list_Category__: {
            /** Data */
            data: components["schemas"]["Category"][];
        };
        /** Data[list[Media]] */
        Data_list_Media__: {
            /** Data */
            data: components["schemas"]["Media"][];
        };
        /** Deleted */
        Deleted: {
            /**
             * Deleted
             * @constant
             */
            deleted: true;
        };
        /** EditorialReview */
        EditorialReview: {
            /** Summary */
            summary: string;
            /** Claims */
            claims: components["schemas"]["ReviewClaim"][];
            /** Gaps */
            gaps: components["schemas"]["ReviewGap"][];
        };
        /** GenerateInput */
        GenerateInput: {
            /**
             * Articledocumentid
             * Format: uuid
             */
            articleDocumentId: string;
            /**
             * Idempotencykey
             * Format: uuid
             */
            idempotencyKey: string;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /**
             * Articledocumentid
             * Format: uuid
             */
            articleDocumentId: string;
            /** Revisionfingerprint */
            revisionFingerprint: string;
            result: components["schemas"]["GeneratedMetadata"];
            /** Cachehit */
            cacheHit: boolean;
            quota: components["schemas"]["QuotaDTO"];
        };
        /** GeneratedMetadata */
        GeneratedMetadata: {
            /** Excerpt */
            excerpt: string;
            /** Metadescription */
            metaDescription: string;
            /** Suggestedtags */
            suggestedTags: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Heading */
        Heading: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heading";
            /**
             * Level
             * @enum {integer}
             */
            level: 2 | 3;
            /** Children */
            children: (components["schemas"]["TextInline"] | components["schemas"]["LinkInline"])[];
        };
        /** ImageBlock */
        ImageBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /**
             * Mediadocumentid
             * Format: uuid
             */
            mediaDocumentId: string;
            /** Alt */
            alt: string;
            /**
             * Caption
             * @default
             */
            caption: string;
        };
        /** LinkInline */
        LinkInline: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
            /** Url */
            url: string;
            /** Children */
            children: components["schemas"]["TextInline"][];
        };
        /** ListBlock */
        ListBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
            /** Ordered */
            ordered: boolean;
            /** Items */
            items: (components["schemas"]["TextInline"] | components["schemas"]["LinkInline"])[][];
        };
        /** LoggedOut */
        LoggedOut: {
            /**
             * Loggedout
             * @constant
             */
            loggedOut: true;
        };
        /** LoginInput */
        LoginInput: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Media */
        Media: {
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
            /** Url */
            url: string;
            /** Publicid */
            publicId: string;
            /** Assetid */
            assetId: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Format
             * @enum {string}
             */
            format: "jpg" | "jpeg" | "png" | "webp";
            /** Credit */
            credit: string;
            /** Sourceurl */
            sourceUrl: string;
            /** License */
            license: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Pagecount */
            pageCount: number;
            /** Total */
            total: number;
        };
        /** Paragraph */
        Paragraph: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paragraph";
            /** Children */
            children: (components["schemas"]["TextInline"] | components["schemas"]["LinkInline"])[];
        };
        /** PrincipalDTO */
        PrincipalDTO: {
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "editor";
        };
        /** PublicArticleCard */
        PublicArticleCard: {
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string;
            category: components["schemas"]["PublicName"];
            author: components["schemas"]["PublicName"];
            cover: components["schemas"]["Cover"];
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /** Readingtimeminutes */
            readingTimeMinutes: number;
            /** Featured */
            featured: boolean;
        };
        /** PublicArticleDetail */
        PublicArticleDetail: {
            /**
             * Documentid
             * Format: uuid
             */
            documentId: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string;
            category: components["schemas"]["PublicName"];
            author: components["schemas"]["PublicName"];
            cover: components["schemas"]["Cover"];
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /** Readingtimeminutes */
            readingTimeMinutes: number;
            /** Featured */
            featured: boolean;
            /** Body */
            body: (components["schemas"]["Paragraph"] | components["schemas"]["Heading"] | components["schemas"]["Quote"] | components["schemas"]["ListBlock"] | components["schemas"]["PublicImageBlock"])[];
            /** Metadescription */
            metaDescription: string;
            /** Tags */
            tags: string[];
            /** Sourcelinks */
            sourceLinks: components["schemas"]["SourceLink"][];
            /** Informationcheckedat */
            informationCheckedAt: string | null;
            /** Covercaption */
            coverCaption: string;
            /** Imagecredit */
            imageCredit: string;
            /** Imagesourceurl */
            imageSourceUrl: string;
            /** Regionlabel */
            regionLabel: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** PublicArticleList */
        PublicArticleList: {
            /** Data */
            data: components["schemas"]["PublicArticleCard"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** PublicCategory */
        PublicCategory: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
        };
        /** PublicCategoryList */
        PublicCategoryList: {
            /** Data */
            data: components["schemas"]["PublicCategory"][];
        };
        /** PublicImageBlock */
        PublicImageBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /**
             * Mediadocumentid
             * Format: uuid
             */
            mediaDocumentId: string;
            /** Alt */
            alt: string;
            /**
             * Caption
             * @default
             */
            caption: string;
            media: components["schemas"]["Cover"];
        };
        /** PublicName */
        PublicName: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PublicSitemapList */
        PublicSitemapList: {
            /** Data */
            data: components["schemas"]["SitemapEntry"][];
        };
        /** QuotaDTO */
        QuotaDTO: {
            /** Used */
            used: number;
            /** Limit */
            limit: number;
            /** Remaining */
            remaining: number;
        };
        /** Quote */
        Quote: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quote";
            /** Children */
            children: (components["schemas"]["TextInline"] | components["schemas"]["LinkInline"])[];
        };
        /** ReviewClaim */
        ReviewClaim: {
            /** Quote */
            quote: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "harga" | "jadwal" | "kontak" | "lokasi" | "lainnya";
            /** Note */
            note: string;
        };
        /** ReviewGap */
        ReviewGap: {
            /** Topic */
            topic: string;
            /** Suggestion */
            suggestion: string;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /**
             * Articledocumentid
             * Format: uuid
             */
            articleDocumentId: string;
            /** Revisionfingerprint */
            revisionFingerprint: string;
            result: components["schemas"]["EditorialReview"];
            /** Cachehit */
            cacheHit: boolean;
            quota: components["schemas"]["QuotaDTO"];
        };
        /** RevisionInput */
        RevisionInput: {
            /** Revision */
            revision: number;
        };
        /** SessionDTO */
        SessionDTO: {
            principal: components["schemas"]["PrincipalDTO"];
            /** Csrftoken */
            csrfToken: string;
        };
        /** SitemapEntry */
        SitemapEntry: {
            /** Slug */
            slug: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SourceLink */
        SourceLink: {
            /** Label */
            label: string;
            /** Url */
            url: string;
            /** Accessedat */
            accessedAt?: string | null;
        };
        /** TextInline */
        TextInline: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Italic
             * @default false
             */
            italic: boolean;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Used */
            used: number;
            /** Limit */
            limit: number;
            /** Remaining */
            remaining: number;
            /**
             * Provider
             * @constant
             */
            provider: "gemini";
            /** Enabled */
            enabled: boolean;
            /**
             * Resetsat
             * Format: date-time
             */
            resetsAt: string;
            /** Busy */
            busy: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_articles_api_public_articles_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: string | null;
                featured?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicArticleList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    article_detail_api_public_articles__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_PublicArticleDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_public_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCategoryList"];
                };
            };
        };
    };
    sitemap_api_public_sitemap_entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSitemapList"];
                };
            };
        };
    };
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_SessionDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_admin_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_SessionDTO_"];
                };
            };
        };
    };
    logout_api_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_LoggedOut_"];
                };
            };
        };
    };
    list_articles_api_admin_articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_ArticleDraft__"];
                };
            };
        };
    };
    create_article_api_admin_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ArticleDraft_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_admin_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ArticleDraft_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_api_admin_articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Deleted_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_article_api_admin_articles__article_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticlePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ArticleDraft_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_article_api_admin_articles__article_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ArticleDraft_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_article_api_admin_articles__article_id__unpublish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ArticleDraft_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_Category__"];
                };
            };
        };
    };
    create_category_api_admin_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Category_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_admin_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Category_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_admin_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Deleted_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_admin_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Category_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_authors_api_admin_authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_Author__"];
                };
            };
        };
    };
    create_author_api_admin_authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Author_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_author_api_admin_authors__author_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Author_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_author_api_admin_authors__author_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Deleted_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_author_api_admin_authors__author_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Author_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_api_admin_media_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_Media__"];
                };
            };
        };
    };
    upload_media_api_admin_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_api_admin_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Media_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_api_admin_media__media_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_Deleted_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editorial_articles_api_admin_editorial_articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_ArticleDraft__"];
                };
            };
        };
    };
    editorial_usage_api_admin_editorial_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
    editorial_generate_api_admin_editorial_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editorial_review_api_admin_editorial_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editorial_apply_api_admin_editorial_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
